### PR TITLE
_Super_ **extra** splash page

### PR DESCRIPTION
**Pull request by justinli610**
It's a slideshow of pretty pictures with slow zoom effects.

- I picked random images, some of which ended up making the text hard to read. Suggestions are welcome (vignette + stippling are applied via CSS so try to avoid dark images and those with vignette already)
- Not sure what to do with the logo/tagline/login (should we still have a box around them? Should it be translucent? Where should it go?)
- Just check this branch out and make changes directly

### CODE REVIEW

**Comment by justinli610** [comment]
Some keyframes:
image
image
image

**Comment by aneedalie** [comment]
Oooohhhhhhhhhhhhhh.

**Comment by aneedalie** [comment]
Looks good. I would just suggest having a white box for the title and login button. Perhaps it can be translucent, or the text can be of the usual colours we have in the app. Your choice :P

**Comment by aneedalie** [comment]
Not a fan of the text shadow though, but I see how it's necessary if you just have text on the images.

**Comment by justinli610** [comment]
Text shadow or translucent box though???

**Pull request merged**
